/**
 * Whiteboard Component
 *
 * Renders SVG diagrams generated by Gemini AI for visual learning.
 * Provides a clean, contained display area for educational visuals.
 *
 * Features:
 * - Instant SVG rendering (no progressive animation for MVP simplicity)
 * - Empty state placeholder when no visual is available
 * - Responsive sizing with max-width constraints
 * - Accessible with ARIA labels
 *
 * Reference:
 * - Bloom_Academia_Frontend.md - Whiteboard Implementation section
 * - Implementation_Roadmap.md - Day 14
 */

'use client'

interface WhiteboardProps {
  svgCode: string | null
}

export function Whiteboard({ svgCode }: WhiteboardProps) {
  if (!svgCode) {
    return (
      <div
        className="w-full h-96 bg-gray-50 rounded-lg flex items-center justify-center border border-gray-200"
        role="img"
        aria-label="Whiteboard area - No visual available"
      >
        <p className="text-gray-400 text-center px-4">
          Visual aids will appear here when the teacher draws diagrams
        </p>
      </div>
    )
  }

  return (
    <div
      className="w-full h-96 bg-white rounded-lg p-8 flex items-center justify-center border border-gray-200 shadow-sm"
      role="img"
      aria-label="Whiteboard with educational diagram"
      dangerouslySetInnerHTML={{ __html: svgCode }}
    />
  )
}
